#! python3

import praw
import pandas as pd
import datetime as dt

reddit = praw.Reddit(client_id='******', \
                        client_secret='*****', \
                        user_agent='redditapp for discord', \
                        username='*****', \
                        password='****')
def redditpost():
	subreddit = reddit.subreddit('dankmemes')
	top_subreddit = subreddit.top(limit=500)
	for submission in subreddit.top(limit=1):
		print(submission.title, submission.id)
		topics_dict = { "title":[], \
		"score":[], \
		"id":[], "url":[], \
		"comms_num": [], \
		"created": [], \
		"body":[]}
		for submission in top_subreddit:
			topics_dict["title"].append(submission.title)
			topics_dict["score"].append(submission.score)
			topics_dict["id"].append(submission.id)
			topics_dict["url"].append(submission.url)
			topics_dict["comms_num"].append(submission.num_comments)
			topics_dict["created"].append(submission.created)
			topics_dict["body"].append(submission.selftext)
redditpost()
topics_data = pd.DataFrame(topics_dict)
topics_data.to_csv('FILENAME.csv', index=False) 
